version: "2.1"
services:
  mongo:
    image: mongo:latest
    ports:
    - 27017:27017
    command: --smallfiles
    
  mongo-client:
    image: mongoclient/mongoclient
    ports:
    - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo
    
# APP  ***************************************************************************************
  crealytics-assignments:
    image: rohanarc/crealytics-assignments
    ports:
    - 9000:9000
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
    
    

